[package]
name = "snow-cursor-capture"
version = "0.1.0"
edition = "2024"

[dependencies]
snow-core = { path = "../snow-core" }
crossbeam-channel.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
proptest = "1"
